export const UPDATE_SEARCH_PARAM = 'UPDATE_SEARCH_PARAM';
export const UPDATE_WATCHLIST = 'UPDATE_WATCHLIST';
export const LOAD_WATCHLIST_FROM_LSTORAGE =
  'LOAD_WATCHLIST_FROM_LSTORAGE';
export const SAVE_WATCHLIST = 'SAVE_WATCHLIST';
